version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=aswiss;User=sa;Password=MySecretPassword!;MultipleActiveResultSets=true;Encrypt=False;
    depends_on:
      - db
    ports:
      - "5001:80"
    networks:
      - proxy-tier

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MySecretPassword!
    ports:
      - "1433:1433"
    networks:
      - proxy-tier

networks:
  proxy-tier:
    driver: bridge